#define LAZER_HIGH         0x10
#define LAZER_LOW          0x11
#define SERVO_SIGNAL_MASK  0xF0
#define SERVO_CENTER 1500
#define THE_ANSWER_TO_THE_ULTIMATE_QUESTION_OF_LIFE_THE_UNIVERSE_AND_EVERYTHING 42